services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    ports:
      - 8080:8080       
      - 7077:7077       
    volumes:
      - .:/mapd-workspace
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    depends_on:
      - spark-master
    volumes:
      - .:/mapd-workspace
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2        
      - SPARK_WORKER_MEMORY=4g      

  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-notebook
    depends_on:
      - spark-master
    ports:
      - 4040:4040       
      - 1234:8888       
    volumes:
      - .:/mapd-workspace
    environment:
      - SPARK_DRIVER_MEMORY=4g      
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell
